// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonReact from "reason-react/lib/es6/src/ReasonReact.js";
import * as PolishPlurals from "polish-plurals";

var component = ReasonReact.reducerComponent("Component3");

var partial_arg = "sekundę";

function getSecondsLabel(param, _) {
  return PolishPlurals.polishPlurals(partial_arg, "sekundy", "sekund", param);
}

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var match = param[/* state */2];
              var seconds = (match[/* currentTime */1] - match[/* startTime */0]) / 1000 | 0;
              var label = getSecondsLabel(seconds, /* () */0);
              var text = "Jesteś na tej stronie już: " + (String(seconds) + (" " + (String(label) + "!")));
              return React.createElement("div", undefined, text);
            }),
          /* initialState */(function () {
              var time = Date.now();
              return /* record */[
                      /* startTime */time,
                      /* currentTime */time
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (_, state) {
              return /* Update */Block.__(0, [/* record */[
                          /* startTime */state[/* startTime */0],
                          /* currentTime */Date.now()
                        ]]);
            }),
          /* subscriptions */(function (param) {
              var send = param[/* send */4];
              return /* :: */[
                      /* Sub */[
                        (function () {
                            return setInterval((function () {
                                          return Curry._1(send, /* Tick */0);
                                        }), 100);
                          }),
                        (function (prim) {
                            clearInterval(prim);
                            return /* () */0;
                          })
                      ],
                      /* [] */0
                    ];
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

export {
  component ,
  getSecondsLabel ,
  make ,
  
}
/* component Not a pure module */
