// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE

import * as Belt_List from "bs-platform/lib/es6/belt_List.js";

var _storageNamespace = "reason-react-todo-list";

function saveTodos(todos) {
  var match = JSON.stringify(Belt_List.toArray(todos));
  if (match !== undefined) {
    localStorage.setItem(_storageNamespace, match);
    return /* () */0;
  } else {
    return /* () */0;
  }
}

function loadTodos() {
  var match = localStorage.getItem(_storageNamespace);
  if (match !== null) {
    return Belt_List.fromArray(JSON.parse(match));
  } else {
    return /* [] */0;
  }
}

export {
  saveTodos ,
  loadTodos ,
  
}
/* No side effect */
